version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 3000:3000
    environment:
      - DB_NAME=shopping
      - DB_CONNECTION=mongodb://shopuser:shoppass@db:27017
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm run dev"

  db:
    image: mongo:latest
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=shopuser
      - MONGO_INITDB_DATABASE=shopping
      - MONGO_INITDB_ROOT_PASSWORD=shoppass
      - ME_CONFIG_MONGODB_URL="mongodb://shopuser:shoppass@server-db-1:27017/"
volumes:
  dbdata:
