version: '3'
services:
  server:
    image: node:12.18.4
    working_dir: /code
    ports: 
      - 3000:3000
    environment:
      - PGUSER=authuser
      - PGHOST=db
      - PGPASSWORD=authpass
      - PGDATABASE=authdb
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm run dev"

  db:
    image: mongo:latest
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=authuser
      - MONGO_INITDB_DATABASE=authdb
      - MONGO_INITDB_ROOT_PASSWORD=authpass
volumes:
  dbdata:
